version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: littlelemon_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - my-db-data:/var/lib/mysql

volumes:
  my-db-data:
