# Generated by Django 4.2.5 on 2023-09-17 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "LittleLemonAPI",
            "0002_menuitem_is_item_of_the_day_order_assigned_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Delivery_Crew"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Delivery_Crew"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_crew",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
