# Generated by Django 4.2.5 on 2023-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0005_order_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
